# -*- coding: utf-8 -*-
"""Assignment_2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-FZ2xaneQwjPf5i5SSfetcttfA4vVYU6

#Francis Ndikum Nji

#Campus ID: RN49536

Solution to Assignment 2 Question 2

#Solution to Question 1
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install graphviz
!apt install libgraphviz-dev
!pip install pygraphviz
!pip install causalgraphicalmodels
!pip install causal-learn

import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

from networkx.drawing.nx_agraph import graphviz_layout, to_agraph
import pygraphviz as pgv

from causalgraphicalmodels import CausalGraphicalModel
from causalgraphicalmodels.examples import fork, chain, collider

# load data
df = pd.read_csv('/content/drive/MyDrive/Fall_2022/IS_800_Causality_New/Assignments/Assignment_2/dataset2.csv')
df

#For statistical data analysis
df.describe()

#To understand the column metadata and datatypes
df.info()

#Check for null values
df.isnull().sum()

"""#Solution to Question 2 - Constraint-based causal discovery Approach
[PC Algorithm](https://causal-learn.readthedocs.io/en/latest/search_methods_index/Constraint-based%20causal%20discovery%20methods/PC.html)
"""

from causallearn.search.ConstraintBased.PC import pc
from causallearn.utils.cit import kci, chisq, fisherz

#convert pandas dataframe to a numpy array, acceptable by our algorithm
df1 = df.to_numpy()

# significance level (alpha) at 0.05
# Here I used “fisherz”: Fisher’s Z conditional independence test because there are no missing values in the data, otherwise “mv_fisherz”
cg = pc(df1, 0.05, fisherz, True, 0, -1)

# visualization using pydot
cols = df.columns
cg.draw_pydot_graph(labels=cols)



"""#Solution to Question 3 - Score-based causal discovery approach
[GES Algorithm](https://causal-learn.readthedocs.io/en/latest/search_methods_index/Score-based%20causal%20discovery%20methods/GES.html#algorithm-introduction)
"""

df1.shape

from causallearn.search.ScoreBased.GES import ges

from causallearn.utils.GESUtils import local_score_BIC


Record = ges(df1, score_func = "local_score_BIC", maxP = None, parameters = None)

# Visualization using pydot
from causallearn.utils.GraphUtils import GraphUtils
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import io

pyd = GraphUtils.to_pydot(Record['G'], labels=cols)
tmp_png = pyd.create_png(f="png")
fp = io.BytesIO(tmp_png)
img = mpimg.imread(fp, format='png')
plt.axis('off')
plt.imshow(img)
plt.show()



"""#Solution to Question 4 - Draw all possible causal graphs for CPDAGs """

graph= CausalGraphicalModel(
    nodes = ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
    edges = [('c','a'),('e','a'),('f','e'),('e','g'),('e','b'),('f','b'),('d','g')]
)
graph.draw()

graph= CausalGraphicalModel(
    nodes = ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
    edges = [('c','a'),('e','a'),('e','f'),('e','g'),('e','b'),('f','b'),('d','g')]
)
graph.draw()